/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ItemAmount { 'amount' : string, 'name' : string }
export interface ItemNote { 'name' : string, 'note' : string }
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'blaster' : string,
  'date' : string,
  'dgms' : string,
  'createdAt' : bigint,
  'lease' : string,
  'address' : string,
  'items' : Array<OrderItem>,
  'quarry' : string,
}
export interface OrderItem { 'qty' : string, 'name' : string }
export interface OrderWithAmounts {
  'order' : Order,
  'amounts' : Array<ItemAmount>,
  'notes' : Array<ItemNote>,
  'driverName' : string,
  'vehicleNumber' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'billDone' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrderWithDriver' : ActorMethod<[bigint, string], undefined>,
  'approveOrderWithVehicle' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignDriverRole' : ActorMethod<[Principal], undefined>,
  'assignManagerRole' : ActorMethod<[Principal], undefined>,
  'getAllDriverNames' : ActorMethod<[], Array<[bigint, string]>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllOrdersWithAmounts' : ActorMethod<[], Array<OrderWithAmounts>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getOrdersByBlaster' : ActorMethod<[string, string], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitOrder' : ActorMethod<
    [string, string, string, string, string, string, Array<OrderItem>],
    bigint
  >,
  'updateItemAmounts' : ActorMethod<[bigint, Array<ItemAmount>], undefined>,
  'updateItemNotes' : ActorMethod<[bigint, Array<ItemNote>], undefined>,
  'updateOrderItems' : ActorMethod<[bigint, Array<OrderItem>], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
