/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'billDone' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderItem = IDL.Record({ 'qty' : IDL.Text, 'name' : IDL.Text });
export const ItemAmount = IDL.Record({ 'amount' : IDL.Text, 'name' : IDL.Text });
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'blaster' : IDL.Text,
  'date' : IDL.Text,
  'dgms' : IDL.Text,
  'createdAt' : IDL.Int,
  'lease' : IDL.Text,
  'address' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'quarry' : IDL.Text,
});
export const OrderWithAmounts = IDL.Record({
  'order' : Order,
  'amounts' : IDL.Vec(ItemAmount),
  'driverName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOrderWithDriver' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignDriverRole' : IDL.Func([IDL.Principal], [], []),
  'assignManagerRole' : IDL.Func([IDL.Principal], [], []),
  'getAllDriverNames' : IDL.Func([], [IDL.Vec(IDL.Tuple([IDL.Nat, IDL.Text]))], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllOrdersWithAmounts' : IDL.Func([], [IDL.Vec(OrderWithAmounts)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByBlaster' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
      ],
      [IDL.Nat],
      [],
    ),
  'updateItemAmounts' : IDL.Func([IDL.Nat, IDL.Vec(ItemAmount)], [], []),
  'updateOrderItems' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'billDone' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderItem = IDL.Record({ 'qty' : IDL.Text, 'name' : IDL.Text });
  const ItemAmount = IDL.Record({ 'amount' : IDL.Text, 'name' : IDL.Text });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'blaster' : IDL.Text,
    'date' : IDL.Text,
    'dgms' : IDL.Text,
    'createdAt' : IDL.Int,
    'lease' : IDL.Text,
    'address' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'quarry' : IDL.Text,
  });
  const OrderWithAmounts = IDL.Record({
    'order' : Order,
    'amounts' : IDL.Vec(ItemAmount),
    'driverName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOrderWithDriver' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignDriverRole' : IDL.Func([IDL.Principal], [], []),
    'assignManagerRole' : IDL.Func([IDL.Principal], [], []),
    'getAllDriverNames' : IDL.Func([], [IDL.Vec(IDL.Tuple([IDL.Nat, IDL.Text]))], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllOrdersWithAmounts' : IDL.Func([], [IDL.Vec(OrderWithAmounts)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByBlaster' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
        ],
        [IDL.Nat],
        [],
      ),
    'updateItemAmounts' : IDL.Func([IDL.Nat, IDL.Vec(ItemAmount)], [], []),
    'updateOrderItems' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
